### ISSUE TITLE
Test accuracy of `predict` methods

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/scikit-learn-knn-regression#26]
Currently, we test the accuracy of `fit` and `kneighbors` against `yaImpute` in [test_port.py](https://github.com/lemma-osu/scikit-learn-knn-regression/blob/fb_add_estimators/tests/test_port.py), but we don't yet test the accuracy of `predict`, which makes it easy for small mistakes that affect results but not functionality (like #23) to go unnoticed.

As [discussed in that issue](https://github.com/lemma-osu/scikit-learn-knn-regression/issues/23#issuecomment-1563472861), we should add some tests that compare prediction results of our estimators to those generated with `yaImpute`.

**Comment by grovduck** [comment]
@aazuspan, a quick note.  I figured out my issue with the predictions and it was how I was calling yaImpute.  I've got some tests for both equal-weights and distance-weighted predictions and they are all passing.  Woot!

**Comment by aazuspan** [comment]
That's great news @grovduck!

Agreed that `test_port.py` could definitely use some clean up... If we could use parametrize like we do in `test_estimators.py` that would be great, but I'm not sure how to account for the fact that GNN and MSN are fit with the `spp` arg while the rest aren't. I suppose we may need two sets of parametrized tests based on whether or not they use ancillary fitting data. But also, given the connection you mention with other issues, it might not be worth spending too much effort cleaning these up yet.

Thanks for the code reference and the explanation of the issue!

**Comment by grovduck** [comment]
@aazuspan - is this worth pushing this more or less as is, knowing that we will be cleaning up the testing data and functions as part of #3 or should we focus on getting #3 in there first?

**Comment by grovduck** [comment]
Resolved by #32
