### ISSUE TITLE
Set up docs

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/scikit-learn-knn-regression#5]
Probably [sphinx](https://www.sphinx-doc.org/en/master/) or [mkdocs](https://www.mkdocs.org/). I've used `sphinx` in the past but would much rather write markdown than restructured text, so I think `mkdocs` is worth looking into.

Apparently `mkdocs` doesn't handle automatically building docs from docstrings, so we'd probably need to throw in [mkdocstrings](https://mkdocstrings.github.io/).

**Comment by grovduck** [comment]
@aazuspan, just a +1 that I like markdown better than rst as well, so I'm supportive of this path.  Having said that, yet another tool/package for me to get familiar with!

**Comment by aazuspan** [comment]
We'll be in the same boat this time! 

One more question. Do you have any thoughts on hosting documentation? I always go with [readthedocs](https://readthedocs.org/) because it's free and easy, but I wasn't sure if you might have a go-to solution through OSU? readthedocs does apparently support [custom domains](https://docs.readthedocs.io/en/stable/custom-domains.html), so if you want it to point to a LEMMA domain, that might be an option. Obviously not something we need to figure out right away, in any case!

**Comment by grovduck** [comment]
readthedocs works for me.  I think there would be very few people that would be coming to the LEMMA website looking for a repo such as this, so I don't think there is any reason that we need to associate it with a custom domain.
