### ISSUE TITLE
Test estimators with `y_fit` data

### ISSUE THREAD

**Issue by aazuspan** [lemma-osu/scikit-learn-knn-regression#53]
While working on #52, I noticed that we don't currently have any tests to confirm the functionality or accuracy of predictions that use separate `y_fit` data. This caused a few bugs (e.g. https://github.com/lemma-osu/scikit-learn-knn-regression/pull/52/commits/7f92a90e62a2da640e920dde418b37b3b226002d) to slip by since the tests were passing even if `y_fit` was ignored.

@grovduck, I'm not 100% sure we need a full-blown port test for this. We already know that we can accurately fit transformers, so maybe all we need to do is confirm that they're getting fit with the correct data? I know it's a pain to add in a whole new set of test data (and I'm not even sure if this is doable with `yaImpute`?), so I'm open to an easy solution, as long as we're confident that it can work as expected. What do you think?

**Comment by grovduck** [comment]
@aazuspan, yep I understand the issue.  I don't think we want to add any new code to the `sknnr.datasets` module, so it seems like the easiest way to test this would be to create the `y` array from a few columns (perhaps `Total_BA`, `UNKN_BA`, and `UNKN_TD`) and use the rest of the columns for `y_fit`?  I think I can pass new attributes when calculating predictions in `yaImpute`, so I don't think that's too difficult.  But perhaps we just need to test this for the default case (`k=5, n_components=None`) for both `GNN` and `MSN` and for reference and target predictions?  Even though neighbors/distances will change, we have tests that cover that.  What do you think?  Am I understanding this correctly?

**Comment by aazuspan** [comment]
> I don't think we want to add any new code to the sknnr.datasets module, so it seems like the easiest way to test this would be to create the y array from a few columns (perhaps Total_BA, UNKN_BA, and UNKN_TD) and use the rest of the columns for y_fit?

Sounds like a good approach!

> I think I can pass new attributes when calculating predictions in yaImpute, so I don't think that's too difficult. But perhaps we just need to test this for the default case (k=5, n_components=None) for both GNN and MSN and for reference and target predictions? Even though neighbors/distances will change, we have tests that cover that. What do you think?

Your proposal sounds more than good enough to me. I wasn't sure if we even needed to compare against `yaImpute` results - we already confirm that all of our estimators fit and predict correctly, which indirectly says that our transformers are fitting and transforming correctly, which theoretically says that fitting the transformer with different data should be covered, right? My thought was that maybe we could just confirm that `y_fit_` gets set when it should be and that `predict` generates different results when you give it different `y_fit` data. Do you think that's too many leaps of logic?

I know the burden of adding more port tests always falls to you, so whatever you're comfortable with here works for me!

**Comment by grovduck** [comment]
> I wasn't sure if we even needed to compare against `yaImpute` results - we already confirm that all of our estimators fit and predict correctly, which indirectly says that our transformers are fitting and transforming correctly, which theoretically says that fitting the transformer with different data should be covered, right? My thought was that maybe we could just confirm that `y_fit_` gets set when it should be and that `predict` generates different results when you give it different `y_fit` data

I can go either way here as well.  The `yaImpute` files shouldn't be too difficult to generate, but I also follow your logic and that seems to be a reasonable approach to testing.  I think I have a personality quirk that I want to be absolutely sure that everything matches, but just testing that we generate different results should be fine.

**Comment by aazuspan** [comment]
There are certainly worse quirks to have! I'll put together a quick PR with the basic functionality test I proposed, and we can see how we feel about it then. Wouldn't hurt to have that even if we end up adding a port test.

**Comment by aazuspan** [comment]
Resolved by #54
